export const MODES = [
  {
    id: "hybrid",
    label: "Hybrid SEO",
    status: "active",
    description: "Combines on-page signals, keyword density, and meta optimization into one unified score.",
    icon: "⚡",
    href: "/hybrid",
  },
  {
    id: "semantic-nlp",
    label: "Semantic NLP SEO",
    status: "active",
    description: "Uses natural language processing to extract entities, map topic clusters, and align content with how search engines semantically understand meaning.",
    icon: "🧠",
    href: "/semantic-nlp",
  },
  {
    id: "rankmath",
    label: "Rank Math Mode",
    status: "coming_soon",
    description: "Mirrors Rank Math's scoring rubric to simulate real plugin output and optimize accordingly.",
    icon: "📐",
    href: null,
  },
  {
    id: "yoast",
    label: "Yoast SEO Mode",
    status: "coming_soon",
    description: "Aligns with Yoast's readability and focus keyphrase analysis for WordPress content.",
    icon: "🟢",
    href: null,
  },
  {
    id: "hcu",
    label: "HCU Recovery Mode",
    status: "coming_soon",
    description: "Diagnoses and repairs content hit by Google's Helpful Content Updates.",
    icon: "🔧",
    href: null,
  },
];
